### ISSUE TITLE
[Task] 앱 출시 전 마지막 잔업 Todo List

### ISSUE THREAD

**Issue by deslog** [JamongSoda/IntoHistory#125]
# 💻 개발 잔업
완료하시면 ✅ 해주세요오

### 노엘
 - [x] notification에서 이름, id등등 정보 엮는거
   - 알림에도 pinName 넣어주어야함
   - noti를 눌렀을때 해당 course 상세 리스트로 보내야함

### 브라운
 - [x] 에디뷰 밑에 버튼 -> ARview로이동
 - [x] ARView에서 ball 클릭 시 미뉴 팝업창 띄우기
     - 버튼넣어서 "지금까지 모은 호국선열"
      - 그럼과 동시에 수집됐다고 데이터 전달해야함
 - [x] #61 
       -> 미뉴가 테스크 진행!!! 

### 미뉴
 - [x] navigation 복구
 - [x] 사망한 Develop branch 복구

### 에디
 - [x] 에디화면 데이터 연동
 - [x] 방문한 핀 색 변경
 - [x] (미뉴가 테스크 가져감) 맵 뷰의 메모리 누수 해결
 - [x] 맵 뷰에서 잘리는 글자 수정
 - [x] 상세 코스 상단 에리어 흰색으로 변경

### 나머지잔업
 - [x] 앱/개발자 정보 viewcontroller 생성 및 i 버튼생성

----

# 📝 Docs 잔업

### 미뉴
 - [x] (모두가 힘을 합침 + 노엘의 디자인) 미리보기 만들기 (앱 캡쳐화면 + 설명 다섯장)
 - [x] 노션 홈페이지 만들기

얼마안남았습니다. 자몽소다 여러분들 화이팅 ✨🥹

----

### 우선순위

★★★★★

### 예상 작업 기간

~0817

**Comment by deslog** [comment]
장하다 다해냈다~ 👀🥳
